# manifests/echo-template/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{.appName}}-config'
  namespace: '{{.namespace}}'
data:
  MESSAGE: '{{.message}}'
---
# manifests/echo-template/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: '{{.appName}}-pod'
  namespace: '{{.namespace}}'
  labels:
    app: '{{.appName}}'
spec:
  containers:
    - name: echo-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "echo $(MESSAGE) && sleep 3600"]
      envFrom:
        - configMapRef:
            name: '{{.appName}}-config'
---
# manifests/echo-template/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: '{{.appName}}-service'
  namespace: '{{.namespace}}'
  labels:
    app: '{{.appName}}'
spec:
  selector:
    app: '{{.appName}}-pod'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
