# manifests/echo-template/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-config
  namespace: echo-one
data:
  MESSAGE: "message in configmap"
---
# manifests/echo-template/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: echo-pod
  namespace: echo-one
  labels:
    app: echo-app
spec:
  containers:
    - name: echo-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "echo $(MESSAGE) && sleep 3600"]
      envFrom:
        - configMapRef:
            name: echo-config
---
# manifests/echo-template/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: echo-one
  labels:
    app: echo-app
spec:
  selector:
    app: echo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
